name = "stl2sdf"
uuid = "799ee158-3091-464b-a66d-482502e2e348"
authors = ["jezekon <78500480+jezekon@users.noreply.github.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelFunctions = "ec8451be-7e33-11e9-00cf-bbf324bd1392"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
BenchmarkTools = "1.6.0"
Dates = "1.11.0"
DelimitedFiles = "1.9.1"
FastGaussQuadrature = "1.0.2"
IterativeSolvers = "0.9.4"
JLD2 = "0.5.12"
KernelFunctions = "0.10.65"
LinearAlgebra = "1.11.0"
NearestNeighbors = "0.4.21"
Printf = "1.11.0"
ProgressMeter = "1.10.3"
SparseArrays = "1.11.0"
StaticArrays = "1.9.13"
Statistics = "1.11.1"
Test = "1.11.0"
WriteVTK = "1.21.1"
